#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).

function display_subdomain_info {
    domain=$1
    subdomain=$2

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"
    do
        #record=$(dig +short "$sub.$domain")
        #type=$(dig +noall +answer "$sub.$domain" | awk '{print $4}')
        #echo "The subdomain $sub is a A record and points to $record"
        dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
    done
}

display_subdomain_info $1 $2
