#!/usr/bin/env bash
# Installs Nginx 

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Add custom HTTP response header to Nginx config
sudo sed -i 's/http {/http {\n    add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conf

# Restart Nginx service
sudo systemctl restart nginx
